FROM node:20-alpine AS builder

WORKDIR /app

# 使用淘宝 npm 镜像源
RUN npm config set registry https://registry.npmmirror.com

COPY frontend/package.json /app/package.json
RUN npm install

COPY frontend /app
RUN npm run build

FROM nginx:1.27-alpine AS runtime

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
